export const SLOTS = ['maze', 'cursor', 'target', 'accent', 'nameplate', 'pong', 'tron'];

export const ITEMS = [
  { key: 'maze:default', default: true, slot: 'maze',   name: 'Default',    color: null, price: 0 },
  { key: 'maze:dark-green', slot: 'maze',   name: 'Dark Green', color: '#2f7a4d', price: 2000 },
  { key: 'maze:teal',       slot: 'maze',   name: 'Teal',       color: '#17a2a6', price: 2400 },
  { key: 'maze:aqua',       slot: 'maze',   name: 'Aqua',       color: '#26d0d6', price: 3000 },
  { key: 'maze:blue',       slot: 'maze',   name: 'Blue',       color: '#3b82f6', price: 3340 },
  { key: 'maze:indigo',     slot: 'maze',   name: 'Indigo',     color: '#6366f1', price: 3400 },
  { key: 'maze:violet',     slot: 'maze',   name: 'Violet',     color: '#8b5cf6', price: 3600 },
  { key: 'maze:red',        slot: 'maze',   name: 'Red',        color: '#e5484d', price: 4000 },
  { key: 'maze:orange',     slot: 'maze',   name: 'Orange',     color: '#f97316', price: 4400 },
  { key: 'maze:yellow',     slot: 'maze',   name: 'Yellow',     color: '#eab308', price: 5000 },

  { key: 'cursor:default', default: true, slot: 'cursor', name: 'Default',    color: null, price: 0 },
  { key: 'cursor:black',    slot: 'cursor', name: 'Black',      color: '#141414', price: 700 },
  { key: 'cursor:red',      slot: 'cursor', name: 'Red',        color: '#e5484d', price: 1400 },
  { key: 'cursor:orange',   slot: 'cursor', name: 'Orange',     color: '#f97316', price: 1540 },
  { key: 'cursor:yellow',   slot: 'cursor', name: 'Yellow',     color: '#eab308', price: 1680 },
  { key: 'cursor:lime',     slot: 'cursor', name: 'Lime',       color: '#84cc16', price: 1820 },
  { key: 'cursor:green',    slot: 'cursor', name: 'Green',      color: '#22c55e', price: 1960 },
  { key: 'cursor:teal',     slot: 'cursor', name: 'Teal',       color: '#14b8a6', price: 2100 },
  { key: 'cursor:aqua',     slot: 'cursor', name: 'Aqua',       color: '#06b6d4', price: 2240 },
  { key: 'cursor:blue',     slot: 'cursor', name: 'Blue',       color: '#3b82f6', price: 2380 },
  { key: 'cursor:indigo',   slot: 'cursor', name: 'Indigo',     color: '#6366f1', price: 2520 },
  { key: 'cursor:violet',   slot: 'cursor', name: 'Violet',     color: '#8b5cf6', price: 2660 },
  { key: 'cursor:pink',     slot: 'cursor', name: 'Pink',       color: '#ec4899', price: 2800 },

  { key: 'target:default', default: true, slot: 'target', name: 'Default',    color: null, price: 0 },
  { key: 'target:orange',   slot: 'target', name: 'Orange',     color: '#f97316', price: 5200 },
  { key: 'target:yellow',   slot: 'target', name: 'Yellow',     color: '#eab308', price: 5460 },
  { key: 'target:green',    slot: 'target', name: 'Green',      color: '#22c55e', price: 5980 },
  { key: 'target:aqua',     slot: 'target', name: 'Aqua',       color: '#06b6d4', price: 6500 },
  { key: 'target:blue',     slot: 'target', name: 'Blue',       color: '#3b82f6', price: 7020 },
  { key: 'target:purple',   slot: 'target', name: 'Purple',     color: '#8b5cf6', price: 7800 },

  { key: 'accent:default', default: true, slot: 'accent', name: 'Default',   color: null, price: 0 },
  { key: 'accent:aqua',    slot: 'accent', name: 'Aqua',     color: '#0ecdf2', price: 6000 },
  { key: 'accent:teal',    slot: 'accent', name: 'Teal',     color: '#12b8a8', price: 6600 },
  { key: 'accent:blue',    slot: 'accent', name: 'Blue',     color: '#3d82f5', price: 7200 },
  { key: 'accent:indigo',  slot: 'accent', name: 'Indigo',   color: '#6c6cf5', price: 7800 },
  { key: 'accent:violet',  slot: 'accent', name: 'Violet',   color: '#9858f6', price: 8000 },
  { key: 'accent:red',     slot: 'accent', name: 'Red',      color: '#e5484d', price: 8800 },
  { key: 'accent:orange',  slot: 'accent', name: 'Orange',   color: '#f97316', price: 9400 },
  { key: 'accent:yellow',  slot: 'accent', name: 'Yellow',   color: '#eab308', price: 10000 },

  { key: 'nameplate:default', default: true, slot: 'nameplate', name: 'Default', color: '#828282', price: 0 },
  { key: 'nameplate:white',        slot: 'nameplate', name: 'White',        color: '#FFFFFF', price: 6000 },
  { key: 'nameplate:blue',         slot: 'nameplate', name: 'Blue',         color: '#9696FF', price: 12000 },
  { key: 'nameplate:green',        slot: 'nameplate', name: 'Green',        color: '#96FF96', price: 20000 },
  { key: 'nameplate:orange',       slot: 'nameplate', name: 'Orange',       color: '#FFC896', price: 28000 },
  { key: 'nameplate:light-red',    slot: 'nameplate', name: 'Light Red',    color: '#FF9696', price: 36000 },
  { key: 'nameplate:pink',         slot: 'nameplate', name: 'Pink',         color: '#FF96FF', price: 40000 },
  { key: 'nameplate:light-purple', slot: 'nameplate', name: 'Light Purple', color: '#D2A0FF', price: 50000 },
  { key: 'nameplate:lime',         slot: 'nameplate', name: 'Lime',         color: '#96FF0A', price: 60000 },
  { key: 'nameplate:yellow',       slot: 'nameplate', name: 'Yellow',       color: '#FFFF0A', price: 72000 },
  { key: 'nameplate:cyan',         slot: 'nameplate', name: 'Cyan',         color: '#05C8FF', price: 80000 },
  { key: 'nameplate:red',          slot: 'nameplate', name: 'Red',          color: '#FF2864', price: 94000 },
  { key: 'nameplate:purple',       slot: 'nameplate', name: 'Purple',       color: '#B428FF', price: 100000 },
  { key: 'nameplate:amber',        slot: 'nameplate', name: 'Amber',        color: '#FFAF00', price: 130000 },
  { key: 'nameplate:rainbow',      slot: 'nameplate', name: 'Rainbow',      color: null, price: 160000,
    colors: ['#FF2864', '#FFAF00', '#FFFF0A', '#96FF96', '#05C8FF', '#9696FF', '#B428FF'] },
  { key: 'nameplate:fiery-red',    slot: 'nameplate', name: 'Fiery Red',    color: null, price: 200000,
    colors: ['#FF2864', '#FFAF00', '#FFFF0A'], speed: 1.2 },

  { key: 'pong:default', default: true, slot: 'pong', name: 'Default', color: null, price: 0 },
  { key: 'pong:teal',    slot: 'pong', name: 'Teal',    color: '#14b8a6', price: 3000 },
  { key: 'pong:blue',    slot: 'pong', name: 'Blue',    color: '#3b82f6', price: 5000 },
  { key: 'pong:indigo',  slot: 'pong', name: 'Indigo',  color: '#6366f1', price: 7000 },
  { key: 'pong:violet',  slot: 'pong', name: 'Violet',  color: '#8b5cf6', price: 9000 },
  { key: 'pong:red',     slot: 'pong', name: 'Red',     color: '#e5484d', price: 11000 },
  { key: 'pong:orange',  slot: 'pong', name: 'Orange',  color: '#f97316', price: 13000 },
  { key: 'pong:gold',    slot: 'pong', name: 'Gold',    color: '#eab308', price: 15000 },

  { key: 'tron:default', default: true, slot: 'tron', name: 'Default', color: null, price: 0 },
  { key: 'tron:teal',    slot: 'tron', name: 'Teal',    color: '#14b8a6', price: 3000 },
  { key: 'tron:blue',    slot: 'tron', name: 'Blue',    color: '#3b82f6', price: 5000 },
  { key: 'tron:indigo',  slot: 'tron', name: 'Indigo',  color: '#6366f1', price: 7000 },
  { key: 'tron:violet',  slot: 'tron', name: 'Violet',  color: '#8b5cf6', price: 9000 },
  { key: 'tron:red',     slot: 'tron', name: 'Red',     color: '#e5484d', price: 11000 },
  { key: 'tron:orange',  slot: 'tron', name: 'Orange',  color: '#f97316', price: 13000 },
  { key: 'tron:gold',    slot: 'tron', name: 'Gold',    color: '#eab308', price: 15000 },
];

export const ITEM_BY_KEY = Object.fromEntries(ITEMS.map((i) => [i.key, i]));

export function getItem(key) {
  return ITEM_BY_KEY[key] || null;
}